name: ocr_env_v1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # PyTorch + CUDA 11.8 (GPU). Para CPU-only, ver nota abajo.
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  # OCR & utilidades
  - pytesseract
  - tesseract
  - pillow
  - pandas
  - numpy
  - jupyter
  - notebook
  - pip
  - pip:
      - PyMuPDF
      - opencv-python-headless>=4.9  # usa 'opencv-python' si necesitas cv.imshow
      - paddleocr
      - easyocr
      - rapidfuzz