import re
OCR_PATTERN = {
    "Aceptacion de Nombramiento":[
        re.compile(r"oficio de aceptaci[oó]n de nombramiento", re.IGNORECASE),
        re.compile(r"camara de representantes", re.IGNORECASE),
        re.compile(r"acepto el cargo", re.IGNORECASE),
        re.compile(r"acepto el nombramiento", re.IGNORECASE),
        re.compile(r"afectuado en mi favor", re.IGNORECASE),
        re.compile(r"tipo de nombramiento", re.IGNORECASE),
        re.compile(r"aceptacion de cargo", re.IGNORECASE),
        re.compile(r"si acepta el cargo", re.IGNORECASE),
    ],
    "Acta de Posesion":[
        re.compile(r"division de personal", re.IGNORECASE),
        re.compile(r"jefatura de personal", re.IGNORECASE),
        re.compile(r"acta de posesion", re.IGNORECASE),
        re.compile(r"tomar posesion", re.IGNORECASE),
        re.compile(r"del cargo", re.IGNORECASE),
        re.compile(r"con asignacion basica", re.IGNORECASE),
        re.compile(r"en constancia se firma", re.IGNORECASE),
    ],
    "Acto Administrativo Nombramiento":[
        re.compile(r"acto administrativo de nombramiento", re.IGNORECASE),
        re.compile(r"por medio de la cual", re.IGNORECASE),
        re.compile(r"se hace un nombramiento", re.IGNORECASE),
        re.compile(r"en la unidad de trabajo", re.IGNORECASE),
        re.compile(r"considerando", re.IGNORECASE),
        re.compile(r"comunicacion acto administrativo", re.IGNORECASE),
        re.compile(r"usted ha sido nombrado", re.IGNORECASE),
        re.compile(r"usted debera manifestar", re.IGNORECASE),
        re.compile(r"continuacion de la resolucion", re.IGNORECASE),
        re.compile(r"si acepta", re.IGNORECASE),
        re.compile(r"el cargo de", re.IGNORECASE),
    ],
    "Certificacion ARL":[
        re.compile(r"seguros", re.IGNORECASE),
        re.compile(r"administradora de riesgos laborales", re.IGNORECASE),
        re.compile(r"se encuentra vinculado", re.IGNORECASE),
    ],
    "Certificado Antecendentes Fiscales":[
        re.compile(r"certificado de antecedentes fiscales", re.IGNORECASE),
        re.compile(r"contraloria", re.IGNORECASE),
        re.compile(r"delegada para investigaciones", re.IGNORECASE),
        re.compile(r"fiscales y jurisdiccion", re.IGNORECASE),
        re.compile(r"no se encuentra", re.IGNORECASE),
        re.compile(r"reportado como responsable fiscal", re.IGNORECASE),
        re.compile(r"administrativa de seguridad ", re.IGNORECASE),
        re.compile(r"certifica", re.IGNORECASE),
        re.compile(r"indice derecho", re.IGNORECASE),
        re.compile(r"no registra", re.IGNORECASE),
        re.compile(r"antecedentes penales", re.IGNORECASE),
        re.compile(r"policia", re.IGNORECASE),
        re.compile(r"firma y sello",re.IGNORECASE),
    ],
    "Certificado Antecendentes Judiciales":[
        re.compile(r"departamento admnistrativo", re.IGNORECASE),
        re.compile(r"certificado de antecedentes judiciales", re.IGNORECASE),
        re.compile(r"policia nacional", re.IGNORECASE),
        re.compile(r"antecedentes penales", re.IGNORECASE),
        re.compile(r"requirimientos judiciales", re.IGNORECASE),
        re.compile(r"no tiene asuntos pendientes", re.IGNORECASE),
        re.compile(r"no tiene asuntos", re.IGNORECASE),
        re.compile(r"indice derecho", re.IGNORECASE),
        re.compile(r"judiciales", re.IGNORECASE),
        re.compile(r"con las autoridades judiciales", re.IGNORECASE),
    ],
    "Certificado Cuenta Bancaria":[
        re.compile(r"bancolombia", re.IGNORECASE),
        re.compile(r"banco", re.IGNORECASE),
        re.compile(r"los siguientes productos", re.IGNORECASE),
        re.compile(r"nombre producto no", re.IGNORECASE),
        re.compile(r"cuenta de ahorros", re.IGNORECASE),
    ],
    "Certificado AFP":[
        re.compile(r"colfondos", re.IGNORECASE),
        re.compile(r"pensiones y cesantias", re.IGNORECASE),
        re.compile(r"se encuentra", re.IGNORECASE),
        re.compile(r"fondo de pensiones", re.IGNORECASE),
        re.compile(r"ley 527 de 1999", re.IGNORECASE),
        re.compile(r"pensiones y cesantias", re.IGNORECASE),
    ],
    "Certificado Antecedentes Disciplinarios":[
        re.compile(r"certificado de", re.IGNORECASE),
        re.compile(r"procuraduria", re.IGNORECASE),
        re.compile(r"certificado de antecendentes", re.IGNORECASE),
        re.compile(r"certificado ordinario", re.IGNORECASE),
        re.compile(r"no registra sanciones", re.IGNORECASE),
        re.compile(r"ni inhabilidades vigentes", re.IGNORECASE),
        re.compile(r"certifica que una vez consultado", re.IGNORECASE),
    ],
    "Certificado Salud":[],
    "Certificado Estudios Profesionales":[
        re.compile(r"certificado de estudio", re.IGNORECASE),
        re.compile(r"institucion de educacion", re.IGNORECASE),
        re.compile(r"escuela tecnica", re.IGNORECASE),
        re.compile(r"certificado de asistencia", re.IGNORECASE),
        re.compile(r"diplomado", re.IGNORECASE),
    ],
    "Certificado Estudios Tecnicos":[
    ],
    "Certificados Experiencia Laboral":[
        re.compile(r"certificado laboral", re.IGNORECASE),
        re.compile(r"constancia de tiempo", re.IGNORECASE),
        re.compile(r"tiempode servicios prestados", re.IGNORECASE),
        re.compile(r"para ex empleados", re.IGNORECASE),
        re.compile(r"fecha de retiro", re.IGNORECASE),
        re.compile(r"la presente constancia se expide", re.IGNORECASE),
        re.compile(r"constancia laboral", re.IGNORECASE),
        re.compile(r"laboro representando", re.IGNORECASE),
        re.compile(r"solicitud del interesado", re.IGNORECASE),
        re.compile(r"coordinadora proyecto", re.IGNORECASE),
        re.compile(r"certifica que", re.IGNORECASE),
        re.compile(r"laboro con", re.IGNORECASE),
        re.compile(r"desempeñandose como", re.IGNORECASE),
        re.compile(r"certificacion laboral", re.IGNORECASE),
        re.compile(r"laborando", re.IGNORECASE),
        re.compile(r"se expide a solicitud del interesado", re.IGNORECASE),
        re.compile(r"registraduria nacional del estado", re.IGNORECASE),
        re.compile(r"se le expide la presente", re.IGNORECASE),
        re.compile(r"labora conmigo", re.IGNORECASE),
        re.compile(r"constancia de tiempo", re.IGNORECASE),
        re.compile(r"tiempo de servicios", re.IGNORECASE),
        re.compile(r"prestados para empleados", re.IGNORECASE),
        ],
    "Compromiso Libreta Militar":[
        re.compile(r"declaraci[oó]n de compromiso de la libreta militar", re.IGNORECASE)],
    "Declaracion Bienes Rentas":[
        re.compile(r"declaraci[oó]n de bienes y rentas", re.IGNORECASE),
        re.compile(r"sigep", re.IGNORECASE),
        re.compile(r"formato declaracion", re.IGNORECASE),
        re.compile(r"de bienes y rentas", re.IGNORECASE),
        re.compile(r"declaracion juramentada", re.IGNORECASE),
        re.compile(r"actividad economica privada", re.IGNORECASE),
        re.compile(r"persona natural", re.IGNORECASE),
        ],
    "Declaracion Demanda Alimentos":[
        re.compile(r"no tengo", re.IGNORECASE),
        re.compile(r"caracter alimentario", re.IGNORECASE),
        re.compile(r"cursen en mi contra", re.IGNORECASE),
        re.compile(r"la ley 311", re.IGNORECASE),
    ],
    "Declaracion Juramentada":[],
    "Diploma Bachiller":[
        re.compile(r"Autorizado por la", re.IGNORECASE),
        re.compile(r"Art 28", re.IGNORECASE),
        re.compile(r"colegio", re.IGNORECASE),
        re.compile(r"colegto", re.IGNORECASE),
    ],
    "Documento Identidad":[
        re.compile(r"CEDULA DE", re.IGNORECASE),
        re.compile(r"documento de identificaci[oó]n", re.IGNORECASE),
        re.compile(r"identificacion personal", re.IGNORECASE),
        re.compile(r"estatura", re.IGNORECASE),
        re.compile(r"expedicion", re.IGNORECASE),
        re.compile(r"lugar de expedici[oó]n", re.IGNORECASE),
        re.compile(r"firma registrador", re.IGNORECASE),
        re.compile(r"Derecho", re.IGNORECASE),
        re.compile(r"indice derecho", re.IGNORECASE),
    ],
    "Examen Medico Ingreso":[
        re.compile(r"valor", re.IGNORECASE),
        re.compile(r"particulares", re.IGNORECASE),
        re.compile(r"recibo no", re.IGNORECASE),
        re.compile(r"servicio medico", re.IGNORECASE),
        re.compile(r"certificado de aptitud", re.IGNORECASE),
        re.compile(r"ha practicado", re.IGNORECASE),
        re.compile(r"el correspondiente examen", re.IGNORECASE),
        re.compile(r"para desempeñar", re.IGNORECASE),
        re.compile(r"historia clinica", re.IGNORECASE),
        re.compile(r"division salud", re.IGNORECASE),
        re.compile(r"constancia medica", re.IGNORECASE),
        re.compile(r"el suscrito medico", re.IGNORECASE),
        re.compile(r"Que en el día de hoy examine", re.IGNORECASE),
        re.compile(r"nombre de", re.IGNORECASE),
        re.compile(r"tipo de examen", re.IGNORECASE),
        re.compile(r"psicofisicamente", re.IGNORECASE),
        re.compile(r"debe renunciar a las siguientes prestaciones", re.IGNORECASE),
        re.compile(r"certificado de aptitud para afiliacion", re.IGNORECASE),
        re.compile(r"examen de afiliacion", re.IGNORECASE),
    ],
    "Formato Autorizacion Descuento":[
        re.compile(r"autorizacion de descuentos", re.IGNORECASE),
        re.compile(r"autorizo al pagador", re.IGNORECASE),
        re.compile(r"corporacion para que descuente de mis emolumentos", re.IGNORECASE),
    ],
    "Formato Compromisos Regimenes Especiales":[],
    "Formato Datos Notficacion Afiliacion":[
        re.compile(r"certificacion de afiliacion", re.IGNORECASE),
        re.compile(r"informacion del afiliado", re.IGNORECASE),
        re.compile(r"informacion de los beneficiarios", re.IGNORECASE),
        re.compile(r"obligatorio de salud", re.IGNORECASE),
        re.compile(r"no valida para traslado entre EPS", re.IGNORECASE),
        re.compile(r"formulario unico", re.IGNORECASE),
        re.compile(r"registro de novedades", re.IGNORECASE),
        re.compile(r"lea las instrucciones", re.IGNORECASE),
        re.compile(r"beneficiario o afiliado adicional", re.IGNORECASE),
        re.compile(r"instructivo para el deligenciamiento", re.IGNORECASE),
        re.compile(r"solicitud de afiliacion", re.IGNORECASE),
        re.compile(r"informacion personal", re.IGNORECASE),
        re.compile(r"reglamento contrato", re.IGNORECASE),
        re.compile(r"de ahorro voluntario", re.IGNORECASE),
        re.compile(r"condiciones para la suscripcion", re.IGNORECASE),
        re.compile(r"SUPERINTENDENCIA FINANCIERA", re.IGNORECASE),
        re.compile(r"datos de notificacion", re.IGNORECASE),
        re.compile(r"y afiliacion", re.IGNORECASE),
    ],
    "Formato Induccion":[
        re.compile(r"induccion", re.IGNORECASE),
        re.compile(r"he recibido la induccion", re.IGNORECASE),
        re.compile(r"fue realizado el processo de induccion", re.IGNORECASE),
        re.compile(r"manual de funciones", re.IGNORECASE),
        re.compile(r"manual de funciones", re.IGNORECASE),
        re.compile(r"video de induccion", re.IGNORECASE),
    ],
    "Formato Tratamiento Datos":[],
    "Formato Declaracion Documenntos Autenticos":[],
    "Formato Prepensionados":[],
    "Formato Verificacion de Requisitos para Vinculacion":[
        re.compile(r"certificaci[oó]n del cumplimiento de requisitos", re.IGNORECASE),
    ],
    "Formulario Afiliacion Caja de Compensacion":[
        re.compile(r"formulario de afiliaci[oó]n a caja de compensaci[oó]n", re.IGNORECASE),
        re.compile(r"inscripcion trabajados", re.IGNORECASE),
        re.compile(r"datos del trabajador", re.IGNORECASE),
        re.compile(r"datos del conyuge", re.IGNORECASE),
        re.compile(r"datos de personas a cargo", re.IGNORECASE),
        re.compile(r"causales de desaprobacion", re.IGNORECASE),
        re.compile(r"para subsidio familiar", re.IGNORECASE),
        re.compile(r"afiliacion aprobad unicamente", re.IGNORECASE),
    ],
    "Formulario Afiliacion Cesantias":[
        re.compile(r"formulario de afiliaci[oó]n a cesant[ií]as", re.IGNORECASE),
    ],
    "Formulario Afiliacion EPS":[],
    "Hoja de Vida de la Funcion Publica":[
        re.compile(r"hoja de vida del funcionario", re.IGNORECASE),
        re.compile(r"formato unico", re.IGNORECASE),
        re.compile(r"LEY 190 DE 1995", re.IGNORECASE),
        re.compile(r"leyes 190 de 1995", re.IGNORECASE),
        re.compile(r"datos personales", re.IGNORECASE),
        re.compile(r"academica", re.IGNORECASE),
        re.compile(r"entidad receptora", re.IGNORECASE),
        re.compile(r"nombre del empleado", re.IGNORECASE),
        re.compile(r"hoja de vida no", re.IGNORECASE),
        re.compile(r"documentos presentados", re.IGNORECASE),
        re.compile(r"oficio nombramiento no", re.IGNORECASE),
        re.compile(r"nombre de la madre", re.IGNORECASE),
        re.compile(r"otros conocimientos", re.IGNORECASE),
        re.compile(r"nombre del cargo", re.IGNORECASE),
        re.compile(r"registro del empleado", re.IGNORECASE),
        re.compile(r"observaciones", re.IGNORECASE),
        re.compile(r"permisos", re.IGNORECASE),
        re.compile(r"firma del servidor publico", re.IGNORECASE),
        re.compile(r"fecha de actualizacion", re.IGNORECASE),
        re.compile(r"nombre del empleado", re.IGNORECASE),

    ],
    "Idoneidad":[],
    "Libreta Militar Certificacion":[],
    "Oficio Notificacion de Nombramiento":[
        re.compile(r"atentamente me permito", re.IGNORECASE),
        re.compile(r"le ha nombrado", re.IGNORECASE),
        re.compile(r"para ocupar el cargo", re.IGNORECASE),
        re.compile(r"si acepta", re.IGNORECASE),
        re.compile(r"sirvase informar a esta secretaria", re.IGNORECASE),
    ],
    "Oficio Postulacion":[],
    "Protocolo_integral_para_la_prevencion_y_orientacion_institucional_frente_a_conductas_de_violencia_sexual_en_el_ambito_laboral_y_contractual":[],
    "Registro Tarjeta Profesional":[],
    "Resolucion de Novedades":[
        re.compile(r"comision de la mesa", re.IGNORECASE),
        re.compile(r"resolucion no", re.IGNORECASE),
        re.compile(r"por la cual", re.IGNORECASE),
        re.compile(r"se causan novedades", re.IGNORECASE),
        re.compile(r"en la unidad de trabajo", re.IGNORECASE),
        re.compile(r"en el personal", re.IGNORECASE),
        re.compile(r"considerando", re.IGNORECASE),
        re.compile(r"resuelve", re.IGNORECASE),
        re.compile(r"continuacion de", re.IGNORECASE),
        re.compile(r"de la resolucion", re.IGNORECASE),
    ],
    "Resolucion Solicitud":[
        re.compile(r"por medio", re.IGNORECASE),
        re.compile(r"de la presente", re.IGNORECASE),
        re.compile(r"me dirijo a usted", re.IGNORECASE),
        re.compile(r"con el objeto de solicitar", re.IGNORECASE),
        re.compile(r"un certificado", re.IGNORECASE),
        re.compile(r"el tiempo de servicio", re.IGNORECASE),
        re.compile(r"atentamente", re.IGNORECASE),
    ],
    "Acta de Grado":[
        re.compile(r"colegio", re.IGNORECASE),
        re.compile(r"acta", re.IGNORECASE),
        re.compile(r"para otorgar el titulo", re.IGNORECASE),
        re.compile(r"el titulo de bachiller", re.IGNORECASE),
        re.compile(r"acta individual", re.IGNORECASE),
        re.compile(r"de certificacion", re.IGNORECASE),
        re.compile(r"acta individual de emision", re.IGNORECASE),                
    ],
    "Compromiso Actualizar Hoja de Vida":[
        re.compile(r"compromiso para actualizar hoja", re.IGNORECASE),
        re.compile(r"me comprometo", re.IGNORECASE),
        re.compile(r"ley 019 de 2012", re.IGNORECASE),
        re.compile(r"con todos los soportes correspondientes", re.IGNORECASE),
    ],
    "Resolucion Renuncia": [
        re.compile(r"por medio de la cual se acepta", re.IGNORECASE),
        re.compile(r"una renuncia", re.IGNORECASE),
        re.compile(r"en la unidad de trabajo", re.IGNORECASE),
        re.compile(r"recibido", re.IGNORECASE),
        re.compile(r"la camara de representantes acepta", re.IGNORECASE),
        re.compile(r"renuncia", re.IGNORECASE),
        re.compile(r"medico de retiro", re.IGNORECASE),
        re.compile(r"acepta la renuncia", re.IGNORECASE),
        re.compile(r"notificacion resolucion", re.IGNORECASE),
        re.compile(r"agradecerle su colobaracion", re.IGNORECASE),
        re.compile(r"renuncia cargo", re.IGNORECASE),
        re.compile(r"me permito renunciar", re.IGNORECASE),
        re.compile(r"aceptado la renuncia", re.IGNORECASE),
        re.compile(r"del cargo", re.IGNORECASE),

    ],
    "Recibo":[
        re.compile(r"unidad de corresponlen", re.IGNORECASE),
        re.compile(r"despacho", re.IGNORECASE),
        re.compile(r"codigo postal", re.IGNORECASE),
        re.compile(r"devolucion", re.IGNORECASE),
        re.compile(r"Reside", re.IGNORECASE),
    ],
    "Certificado de Curso":[
        re.compile(r"la escuela superior", re.IGNORECASE),
        re.compile(r"hace constar", re.IGNORECASE),
        re.compile(r"asistio al", re.IGNORECASE),
        re.compile(r"asistio al primer", re.IGNORECASE),
        re.compile(r"asistio al segundo", re.IGNORECASE),
        re.compile(r"asistio al tercer", re.IGNORECASE),
        re.compile(r"realizado en", re.IGNORECASE),
        re.compile(r"certifica que", re.IGNORECASE),
        re.compile(r"actualizacion en descentralizacion", re.IGNORECASE),
        re.compile(r"participo en el curso", re.IGNORECASE),
        re.compile(r"curso de", re.IGNORECASE),
        re.compile(r"aprobo", re.IGNORECASE),
        re.compile(r"el curso", re.IGNORECASE),
    ],
    "Certificado taller":[
        re.compile(r"certificado", re.IGNORECASE),
        re.compile(r"participo en", re.IGNORECASE),
        re.compile(r"taller regional", re.IGNORECASE),
        re.compile(r"sobre", re.IGNORECASE),
        re.compile(r"con una intensidad", re.IGNORECASE),
    ],
    "Certificado seminario": [
        re.compile(r"el seminario", re.IGNORECASE),
        re.compile(r"participo", re.IGNORECASE),
        re.compile(r"certifica que", re.IGNORECASE),
    ],
    "credencial": [
        re.compile(r"registraduria nacional", re.IGNORECASE),
        re.compile(r"declaramos", re.IGNORECASE),
        re.compile(r"se le expide", re.IGNORECASE),
        re.compile(r"la presente credencial", re.IGNORECASE),
    ],
    "Documento Declaracion":[
        re.compile(r"los autorizo", re.IGNORECASE),
        re.compile(r"para verificar", re.IGNORECASE),
        re.compile(r"respectivas", re.IGNORECASE),
        re.compile(r"manifiesto a ustedes", re.IGNORECASE),
        re.compile(r"bajo la gravedad de juramento", re.IGNORECASE),
        re.compile(r"no he recibido", re.IGNORECASE),
    ],
    "Resolucion vacacional":[
        re.compile(r"descuente", re.IGNORECASE),
        re.compile(r"mis emolumentos", re.IGNORECASE),
        re.compile(r"no haya completado", re.IGNORECASE),
    ],
}